# Generated by Django 3.1.3 on 2020-11-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publication_house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libmgmt.publicationhouse'),
            preserve_default=False,
        ),
    ]
