# Generated by Django 3.1.3 on 2020-11-24 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0006_auto_20201123_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booksissued',
            name='issue_date',
            field=models.DateField(default=datetime.date(2020, 11, 24)),
        ),
    ]
