# Generated by Django 3.1.3 on 2020-11-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmt', '0008_auto_20201124_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
